#include <stdio.h>
#include <math.h>

#define ESPRESSO_BEANS 8 
#define ESPRESSO_WATER 30
#define ESPRESSO_PRICE 3.5

#define CAPPUCCINO_BEANS 8
#define CAPUCCINO_WATER 30
#define CAPPUCCINO_MILK 70
#define CAPPUCCINO_PRICE 4.5

#define MOCHA_BEANS 8
#define MOCHA_WATER 39
#define MOCHA_MILK 160
#define MOCHA_CHOCOLATE_SYRUP 30
#define MOCHA_PRICE 5.5

#define THRESHOLD_BEANS 20
#define THRESHOLD_WATER 60
#define THRESHOLD_MILK 200
#define THRESHOLD_CHOCOLATE_SYRUP 50

#define ADMIN_PASSWORD 1212
